### ISSUE TITLE
Quero um site padronizado

### ISSUE THREAD

**Issue by KarenF** [aceleradora-TW/conhecimento-livre#100]
**Como** Carlos
**Quero** um site padronizado
**Para** ter melhor usabilidade da plataforma

**Critérios de aceitação:**
- Link para github e facebook no cabeçalho;
- Deve haver uma lista verde com 3 ícones não clicáveis na página inicial ;
- ícones devem estar em português;
- Textos devem estar centralizados nos "cards";
- Próximas aulas devem estar contidas dentro de uma caixa de outra cor;
- Nome do autor não deve estar sublinhado;
- Título das aulas no vídeo devem aparecer apenas quando selecionada a aula;
- Todos os nomes das linguagens devem estar em caixa alta;
- Nome do autor deve ocupar apenas uma linha;
- Sub-título na página do auto deve estar alinhado com os "cards";
- Cursos do autor devem estar dentro de uma caixa.

**Comment by mvoliveira** [comment]
Não precisamos colocar o "Como, Quero, Para" no título, foi acordado que seria apenas o "Quero" para facilitar a leitura das issues no momento da Demo!

**Comment by mvoliveira** [comment]
1° - Evitar o uso de jargões(Header, Hero, Box)  técnicos nas escrita dos **Critérios de aceitação**, isso pode ser descrito em outro momento na ISSUE como **Detalhes Técnicos**. Estes nomes poderiam ser trocados facilmente por Cabeçalho, Listra com ícones na página inicial, campo.

Sugiro manter um padrão de escrita para facilitar a leitura.
Como está no momento:

- Todos os ícones em português;
- Centralização dos textos nos cards;

Opção a isto:

- Icones devem estar em português;
- Textos devem estar centralizados nos "cards";
