### ISSUE TITLE
Quero acessar o usuário de administrador

### ISSUE THREAD

**Issue by KarenF** [aceleradora-TW/conhecimento-livre#101]
**Como** Leco
**Quero** acessar o usuário de administrador
**Para** manipular os dados da plataforma

**Critérios de aceitação:**
- Admin deve conseguir inserir a senha;
- Após autenticação da senha o administrador deve ser redirecionado para página com os dados ;
- Se houver algum erro o administrador deve poder inserir a senha novamente;
- Permitir acesso a próximas páginas apenas após autenticação do admin.

**Comment by mvoliveira** [comment]
Não precisamos colocar o "Como, Quero, Para" no título, foi acordado que seria apenas o "Quero" para facilitar a leitura das issues no momento da Demo!

**Comment by mvoliveira** [comment]
1° - Caso tenha sido solicitado pelo P.O um alerta com senha inválida, isso deve ser descrito na ISSUE.
2° - "Página do Administrador" não é um critério descritivo, fica obsoleto para quem vai ler e desenvolver a ISSUE;
