### ISSUE TITLE
Quero visualizar os dados cadastrados na plataforma

### ISSUE THREAD

**Issue by KarenF** [aceleradora-TW/conhecimento-livre#102]
**Como** Leco
**Quero** visualizar os dados cadastrados na plataforma
**Para** analisá-los

**Critérios de aceitação:**
- Lista com os dados dos autores, cursos e aulas;
- Conseguir visualizar opção de inserir e atualizar os dados;
- Conseguir excluir os dados existentes.

**Comment by mvoliveira** [comment]
Não precisamos colocar o "Como, Quero, Para" no título, foi acordado que seria apenas o "Quero" para facilitar a leitura das issues no momento da Demo!

**Comment by mvoliveira** [comment]
**Critérios de aceitação:**

Lista com os dados;
_Quais dados? Isso deve ser acordado com o P.O e descrito na issue_

**Faltam critérios ou uma nova história para o momento em que não existirem dados cadastrados.**
