### ISSUE TITLE
Quero editar os dados

### ISSUE THREAD

**Issue by KarenF** [aceleradora-TW/conhecimento-livre#104]
**Como** Leco
**Quero** editar os dados
**Para** atualizá-los na plataforma

**Critérios de aceitação:**
- Conseguir inserir e atualizar os dados do autor;
- Conseguir inserir e atualizar os dados do curso;
- O curso deve receber uma imagem padrão caso o admin não insira uma imagem no curso;
- Conseguir inserir e atualizar os dados das aulas;
- Deve haver alerta de confirmação da deleção.

**Comment by mvoliveira** [comment]
Não precisamos colocar o "Como, Quero, Para" no título, foi acordado que seria apenas o "Quero" para facilitar a leitura das issues no momento da Demo!

**Comment by mvoliveira** [comment]
Faltam critérios:
1° - No momento em que não existem dados para serem atualizados, o que ocorre?
2° - Caso o P.O tenha solicitado a modal de confirmação, ela deveria aparecer aqui.
