### ISSUE TITLE
Quero testar o modo teatro

### ISSUE THREAD

**Issue by KarenF** [aceleradora-TW/conhecimento-livre#110]
**Como** Yasser
**Quero** testar o modo teatro
**Para** saber a opinião do usuário

**Critérios de aceitação:**
- Ter o relatório de, no mínimo, 7 testes.

**Comment by mvoliveira** [comment]
Não precisamos colocar o "Como, Quero, Para" no título, foi acordado que seria apenas o "Quero" para facilitar a leitura das issues no momento da Demo!
