### ISSUE TITLE
Quero que meu site responda a um novo domínio

### ISSUE THREAD

**Issue by aceleradora12** [aceleradora-TW/conhecimento-livre#138]
**Como** Leco
**Quero** que meu site responda a um novo domínio
**Para** que as pessoas consigam acessar o site com mais facilidade

**Critérios de aceitação:**

- Redirecionar o site para www.conhecimentolivre.com.br;
- Criar subdomínios.

**Comment by mvoliveira** [comment]
Aqui poderiam ser descritos os detalhes que foram comentados no Show Case, sobre o Heroku, que talvez ele mude de IP, e isto deve ser conferido, acho importante deixar explicito, pois pode vir a gerar problemas.

"Criar subdomínios, se gratuítos." Quais? E vinculados a qual ambiente da app?
