### ISSUE TITLE
Quero receber dados de acesso a plataforma

### ISSUE THREAD

**Issue by aceleradora12** [aceleradora-TW/conhecimento-livre#140]
**Como** Leco
**Quero** receber dados de acesso a plataforma
**Para** saber se os usuários estão utilizando o site

**Critérios de aceitação:**

- Receber o mapa de calor;
- Receber informação sobre a página em que o usuário saiu do site através do Google Analytics;
- Receber a duração de acesso do usuário por página através do Google Analytics.

**Comment by mvoliveira** [comment]
Acredito que o mapa de calor que foi conversado, tratava-se de cliques nos elementos do site. Sendo assim o Google Analytics não possui essa funcionalidade até onde eu sei.

Aqui existem algumas opções de ferramentas: http://blog.cicloagenciadigital.com.br/ferramentas-de-web-analytics-essenciais/

Algumas possuem versões trial que podemos testar, assim como HotJar.

**Comment by mvoliveira** [comment]
Como o Leco irá receber esses dados que estão na história?
