### ISSUE TITLE
Quero  acessar uma página de erro

### ISSUE THREAD

**Issue by MauricioSalin** [aceleradora-TW/conhecimento-livre#99]
**Como** Carlos
**Quero** acessar uma página de erro
**Para** ser informado que a página não foi encontrada

**Critérios de aceitação:**
- Ser redirecionado para página de erro sempre que entrar em uma url inexistente.
- Ser redirecionado para página de erro sempre que uma procura no banco falhe.

**Comment by mvoliveira** [comment]
Não precisamos colocar o "Como, Quero, Para" no título, foi acordado que seria apenas o "Quero" para facilitar a leitura das issues no momento da Demo!
